@startuml ag_level1
!include <C4/C4_Container>
title Automata Games Level 1 Architecture
Person(ubob, "Bob", "An AG account holder")
System_Ext(namecheap, "Name Cheap", "Domain Name Provider: Resolves to Heroku")
System_Ext(hk, "Heroku", "Cloud Provider hosting AG")
System(ag, "Automata Games", "Online Multiplayer Gaming Platform")
System_Ext(sendgrid, "SendGrid", "Email as a Service")

Rel_D(ubob, namecheap, "Visits AG", "HTTPS")
Rel(namecheap, hk, "Resolves to Heroku", "DNS")
Rel(hk, ag, "Routes to", "HTTPS")
Rel(ag, sendgrid, "Sends Emails", "ActionMailer")
Rel(sendgrid, ubob, "Sends Mail", "email")
Rel(ag, ubob, "Web Page", "HTML")
@enduml