@startuml overview
title Rails Server Client Interaction with a normal SPA not using InertiaJS
participant Server as s
participant Client as c

c -> s: GET /
s -> c: 200 text/html
|||
c <-> s: GET /main.css
c <-> s: GET /app.js
note right
JS App initializes
end note

c -> c: Navigate to settings page with button click

note right
client side routing updates browser history and url
but does not do a full page load
and re-renders components
end note

c -> s: GET(AJAX) /api/some-data
note right
New components require some data
request via ajax
end note

s -> c: 200 text/json
c -> c: Update components, re-render component(s)
@enduml

@startuml inertiajs
title Rails Server Client Interaction with InertiaJS SPA
participant Server as s
participant Client as c

c -> s: GET /
s -> c: 200 text/html
|||
c <-> s: GET /main.css
c <-> s: GET /app.js
note right
JS App initializes
end note

c -> s: 200 /settings
note right
Navigate to settings page with button click
end note

s -> c: 304 text/json
note right
304 response does not re-render page
Body includes name of front end page to render
And any date we needed
end note

c -> c: Render components

@enduml