[alias]
quick_dev = [
    "watch",
    "-q",
    "-c",
    "-w",
    "examples/quick_dev.rs",
    "-x",
    "run -q --example quick_dev",
]

live_reload = ["watch", "-q", "-c", "-w", "src/", "-x", "run"]
live-test = ["watch", "-q", "-c", "-w", "src/", "-w", "tests/", "-x", "test"]
