# Docker-Compose definition for a locally mapped Postgres database and Redis database

services:
  server:
    build: .
    environment:
      DATABASE_URL: postgres://pgdev:pgdev@db:5432/dev
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: pgdev
      POSTGRES_PASSWORD: pgdev
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432