# Docker compose for local development and testing of the server and client
# with a Postgres database.

services:
  # server tests the production Dockerfile build
  server:
    profiles: [ prod ]
    build: .
    environment:
      DATABASE_URL: postgres://pgdev:pgdev@db:5432/dev
    ports:
      - 3000:3000
    depends_on:
      - db

  # Development server - live reload for back end server
  # This image will install diesel and run DB setup on launch
  dev-server:
    build:
      context: .
      dockerfile: docker/dev-server.dockerfile
    environment:
      DATABASE_URL: postgres://pgdev:pgdev@db:5432/dev
    volumes:
      - ./server:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  # Development client - live reload for front end client
  dev-client:
    build:
      context: .
      dockerfile: docker/dev-client.dockerfile
    environment:
      - SERVER_HOST=dev-server
    volumes:
      - ./client:/app
    ports:
      - 5173:5173

  # Postgres database
  db:
    image: postgres
    environment:
      POSTGRES_USER: pgdev
      POSTGRES_PASSWORD: pgdev
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432
