# Docker-Compose definition for a locally mapped Postgres database and Redis database

version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pgdev
      POSTGRES_PASSWORD: pgdev
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432