-- Your SQL goes here
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  handle VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_salt VARCHAR(255) NOT NULL,
  password_hash BYTEA NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
