name: Fly Deploy

on:
	push:
		branches: [ release ]

jobs:
	deploy:
		name: Deploy to Fly
		runs-on: ubuntu-latest
		concurrency:
			group: fly-deploy
			cancel-in-progress: false
		steps:
			- uses: actions/checkout@v4
			- uses: superfly/flyctl-actions/setup-flyctl@master
			- run: flyctl deploy
				env:
					FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
